insert into user values(1, 'coufran', '6eed84a9f80ad64ec927ec0012e2602a');

insert into title values(1, '现金', 'ASSETS');
insert into title values(2, '在线支付', 'ASSETS');
insert into title values(3, '储蓄卡', 'ASSETS');
insert into title values(4, '社会保障', 'ASSETS');
insert into title values(5, '投资理财', 'ASSETS');
insert into title values(6, '应收预付', 'ASSETS');
insert into title values(7, '应付预收', 'LIABILITY');
insert into title values(8, '信用卡', 'LIABILITY');
insert into title values(9, '消费贷', 'LIABILITY');
insert into title values(10, '储值卡', 'ASSETS');
insert into title values(11, '收入', 'PROFIT');
insert into title values(12, '支出', 'LOSS');

insert into account values(null, '钱包', 28600, 1);
insert into account values(null, '支付宝', 0, 2);
insert into account values(null, '微信', 50454, 2);
insert into account values(null, '北京银行', 15088, 3);
insert into account values(null, '建设银行', 0, 3);
insert into account values(null, '农村信用社', 0, 3);
insert into account values(null, '招商银行', 0, 3);
insert into account values(null, '农业银行', 0, 3);
insert into account values(null, '网商银行', 0, 3);
insert into account values(null, '邮政储蓄银行', 1495, 3);
insert into account values(null, '浦发银行', 0, 3);
insert into account values(null, '工商银行', 12760, 3);
insert into account values(null, '医保', 0, 4);
insert into account values(null, '住房公积金', 2504592, 4);
insert into account values(null, '天弘上证50指数C', 0, 5);
insert into account values(null, '广发中证医疗指数C',234254, 5);
insert into account values(null, '易方达中小盘混合', 105284, 5);
insert into account values(null, '长江证券', 0, 5);
insert into account values(null, '黄金', 359, 5);
insert into account values(null, '建信纯债债券', 1042170, 5);
insert into account values(null, '富国信用债债券A/B', 1043217, 5);
insert into account values(null, '银河创新成长混合', 0, 5);
insert into account values(null, '广发双擎升级混合', 0, 5);
insert into account values(null, '招商信用添利债券', 1037887, 5);
insert into account values(null, '招商中证白酒指数分级', 676167, 5);
insert into account values(null, '招商双债增强债券C', 2624347, 5);
insert into account values(null, '华泰柏瑞季季红债券', 1599790, 5);
insert into account values(null, '景顺长城新兴成长混合', 1960408, 5);
insert into account values(null, '天弘中证500指数C', 0, 5);
insert into account values(null, '天弘中证银行指数C', 84962, 5);
insert into account values(null, '天弘通利混合', 1644666, 5);
insert into account values(null, '天弘创业板ETF联接C', 101485, 5);
insert into account values(null, '天弘沪深300指数C', 134915, 5);
insert into account values(null, '大成标普500指数', 811818, 5);
insert into account values(null, '大成纳斯达克100指数', 2206743, 5);
insert into account values(null, '安信目标收益债券A', 1807190, 5);
insert into account values(null, '安信新回报灵活配置混合', 936522, 5);
insert into account values(null, '博时中债债券指数A', 1027016, 5);
insert into account values(null, '博时合惠货币B', 5062632, 5);
insert into account values(null, '余额宝', 16526868, 5);
insert into account values(null, '工资应收', 15008, 6);
insert into account values(null, '其他预付', 217060, 6);
insert into account values(null, '其他应收', 33430, 6);
insert into account values(null, '加油预付（加油卡）', 43267, 6);
insert into account values(null, '车险预付', 75661, 6);
insert into account values(null, '房租预付', 483475, 6);
insert into account values(null, '借出款', 2495000, 6);
insert into account values(null, '其他应付', -190, 7);
insert into account values(null, '欠款', -8667500, 7);
insert into account values(null, '招商银行信用卡', -1989, 8);
insert into account values(null, '晋商银行信用卡', 0, 8);
insert into account values(null, '蚂蚁花呗', -429847, 9);
insert into account values(null, '京津冀互联互通卡_手环', 101, 10);
insert into account values(null, '京津冀互联互通卡_手机', 500, 10);
insert into account values(null, '北京市政一卡通', 1150, 10);
insert into account values(null, '太原公交卡', 0, 10);
insert into account values(null, '工资', 0, 11);
insert into account values(null, '奖金', 0, 11);
insert into account values(null, '兼职', 0, 11);
insert into account values(null, '收红包', 0, 11);
insert into account values(null, '生活费', 0, 11);
insert into account values(null, '报销', 0, 11);
insert into account values(null, '借入款', 0, 11);
insert into account values(null, '投资收益', 0, 11);
insert into account values(null, '公积金', 0, 11);
insert into account values(null, '其他收入', 0, 11);
insert into account values(null, '租金', 0, 11);
insert into account values(null, '社保金', 0, 11);
insert into account values(null, '生意收入', 0, 11);
insert into account values(null, '餐饮', 0, 12);
insert into account values(null, '交通', 0, 12);
insert into account values(null, '购物', 0, 12);
insert into account values(null, '居住', 0, 12);
insert into account values(null, '娱乐', 0, 12);
insert into account values(null, '教育', 0, 12);
insert into account values(null, '医疗', 0, 12);
insert into account values(null, '人情', 0, 12);
insert into account values(null, '投资亏损', 0, 12);
insert into account values(null, '其他', 0, 12);
insert into account values(null, '邮费', 0, 12);
insert into account values(null, '发红包', 0, 12);
